#!/usr/bin/env bash
#
# Run file for CodeOcean.com
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
matlab -nodisplay -r "addpath(genpath('.')); run"